name: anniv_46_admin_app
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

# ------------------- PACKAGES -------------------
dependencies:
  flutter:
    sdk: flutter

  # Utils
  logger: ^2.4.0
  http: ^1.2.2
  intl: ^0.19.0
  url_launcher: ^6.3.0
  get_storage: ^2.1.1
  connectivity_plus: ^5.0.2
  lottie: ^3.1.2
  animated_digit: ^3.2.3
  liquid_pull_refresh: ^1.0.6
  shimmer: ^3.0.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6

  # Splash screen
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.0

# ./------------------- PACKAGES END -------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  change_app_package_name: ^1.3.0


flutter:
  uses-material-design: true

  # ------------------- LOCAL ASSETS -------------------
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/

  # ------------------- FONT ASSETS -------------------
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
