// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0tvsvJdqSBmFGZLh5wzbhABW-qX57TPs',
    appId: '1:760013082434:web:1fe16e4e6acd647f6cc2db',
    messagingSenderId: '760013082434',
    projectId: 'anniv46th',
    authDomain: 'anniv46th.firebaseapp.com',
    storageBucket: 'anniv46th.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeDXUiq1r17plTVnaWE2NDrfZzKPOMGMU',
    appId: '1:760013082434:android:6a7ee5d7d33c72436cc2db',
    messagingSenderId: '760013082434',
    projectId: 'anniv46th',
    storageBucket: 'anniv46th.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjJukU5-Sd7dvlcxodzSSfUEw9GVJsgcQ',
    appId: '1:760013082434:ios:963b2224aedfed9b6cc2db',
    messagingSenderId: '760013082434',
    projectId: 'anniv46th',
    storageBucket: 'anniv46th.appspot.com',
    androidClientId: '760013082434-6ckftfl6i3us9t0ua09u088m8a7c8scr.apps.googleusercontent.com',
    iosClientId: '760013082434-jbi7ul27k8bu2pufe6h45269lucic2eb.apps.googleusercontent.com',
    iosBundleId: 'com.polyphonicsapps.preregistration',
  );

}